export const PARSE_PAYLOAD = 'PARSE_PAYLOAD';
export const LOGOUT = 'LOGOUT';
export const IMPLICIT_GRANT_LINK = 'IMPLICIT_GRANT_LINK';
export const GET_USER_INFO = 'GET_USER_INFO';
export const GET_REPOSITORIES = 'GET_REPOSITORIES';
export const GET_PIPELINE_STATUS = 'GET_PIPELINE_STATUS';
export const CALL_BITBUCKET_API = 'CALL_BITBUCKET_API';
export const TOGGLE_SELECTED_REPOSITORY = 'TOGGLE_SELECTED_REPOSITORY';
