export const PURGE_AUTH = 'PURGE_AUTH';
export const STORE_AUTH = 'STORE_AUTH';
export const SET_USER_INFO = 'SET_USER_INFO';
export const CLEAR_USER_INFO = 'CLEAR_USER_INFO';
export const SET_REPOSITORIES = 'SET_REPOSITORIES';

export const SET_PIPELINES = 'SET_PIPELINES';
export const SET_SELECTED_REPOSITORY = 'SET_SELECTED_REPOSITORY';

